@startuml
class Flail extends weapons
class Sword extends weapons
class Handaxe extends weapons
class Potions extends Equipment
class Shield extends Equipment
class Vampire extends Characters
class Warrior extends Characters
class VampireAttack extends weapons
class BerserkPotion extends potions
class Bite extends vampireAttack
class Claw extends vampireAttack
class LastBreathPotion extends potions
class MalphitePotion extends potions
class SeagullPotion extends potions
class TwitterPotion extends potions
class SoulSyphon extends VampireAttack
class WarriorActions extends Warrior

class Main {
    +main(args: String[]): void
}
abstract class Equipment {
    #name: String
    #cuantity: int
    +Equipment(name: String, cuantity: int)
}
abstract class Characters {
    #name: String
    #heatlh: double
    +Characters(name: String, health: double)
    }
abstract class Weapons {
    -damage: double
    -accuracy: double
    +weapons(name: String, damage: double, accuracy: double)
    +getDamage(): double
    +getAccuracy(): double
    +setDamage(damage: double): void
    +setAccuracy(accuracy: double): void
  }
class Flail{
    +Flail(damage: double, accuracy: double)
    +FlailAttack(damage: double, accuracy: double): void
    +hit(): void
}
class Sword{
    +Sword(damage: double, accuracy: double)
    +swordAttack(damage: double, accuracy: double): void
    +hit(): void
}
class Handaxe{
    +handaxe(damage: double, accuracy: double)
    +handaxeAttack(damage: double, accuracy: double): void
    +hit(): void
}

class Shield{
    +shield(name: String, cuantity: int)
    +isShieldActive: boolean
    +activateShield(): boolean
    +deactivateShield(): boolean
    +setName(name: String): void
    +setCuantity(cuantity: int): void
    +getName(): String
    +getCuantity(): int
    +shieldUp(warrior: Warrior): void
    +shieldDown(warrior: Warrior): void
}
class Vampire{
    +vampire(name: String, health: double, attack: double, accuracy: double)
    +setName(name: String): void
    +setHealth(health: double): void
    +getHealth(): double
    +getName(): String
}
class VampireAttack{
    +vampireAttack(damage: double, accuracy: double)
    +vampireAttacks(): void
}
class Warrior{
    +warrior(name: String, health: double, attack: double, accuracy: double)
    +setName(name: String): void
    +setHealth(health: double): void
    +getHealth(): double
    +getName(): String
    +setShieldActive(shieldActive: boolean): void
    +setShieldInactive(shieldActive: boolean): void
    +getShieldActive(): boolean
    +getHieldInactive(): boolean
}
class BerserkPotion{
    +berserkPotion(name: String, cuantity: int)
    +activateBerserkPotion(): boolean
    +deactivateBerserkPotion(): boolean
    +berserkPotion(warrior: Warrior): void
}
class Bite{
    +bite(damage: double, accuracy: double)
    +biteAttack(): void
}
class Claw{
    +claw(damage: double, accuracy: double)
    +clawAttack(): void
}
class GeneralManager{
    +ShieldCounter: int
    +iniciate(): void
    +combat(): void
}
class LastBreathPotion{
    +LastBreathPotion(name: String, cuantity: int)
    +activateLastBreathPotion(): boolean
    +deactivateLastBreathPotion(): boolean
    +LastBreathPotion(warrior: Warrior): void
}
class MalphitePotion{
    +MalphitePotion(name: String, cuantity: int)
    +activateMalphitePotion(): boolean
    +deactivateMalphitePotion(): boolean
    +rockSolid(warrior: Warrior): void
}
class Potions {
    +berserkActive: boolean
    +healthActive: boolean
    +rockActive: boolean
    +eyeActive: boolean
    +twitterActive: boolean
    +Potions(name: String, cuantity: int)
    +setName(name: String): void
    +setCuantity(cuantity: int): void
    +getName(): String
    +getCuantity(): int
}
class SeagullPotion{
    +SeagullPotion(name: String, cuantity: int)
    +activateeyePotion(): boolean
    +deactivateeyePotion(): boolean
    +seagullEye(warrior: Warrior): void
}
class SoulSyphon{
    +SoulSyphon(damage: double, accuracy: double)
    +soulAttack(): void
}
class TwitterPotion{
    +TwitterPotion(name: String, cuantity: int)
    +activatetwitterPotion(): boolean
    +deactivatetwitterPotion(): boolean
    +twitterEssence(warrior: Warrior): void
}
class WarriorActions{
    +WarriorActions(name: String, health: double)
    +attackFlail(): void
    +attackSword(): void
    +attackHandaxe(): void
    +checkEquipment(): void
    +useShield(): void
}
@enduml