@startuml
Controller --> DataBase


Client --|> Entity
Item --|> Entity

ItemDataBase --|> DataBase
ClientDataBase --|> DataBase

ItemDataBase --> Entity
ClientDataBase --> Entity

DataBase --> FileReader


Abstract DataBase{
    List BaseList

    ReadFile()
    WriteFile()

}

Abstract Entity{
    String name
    String id

    void identify()
}

Class ItemDataBase{
    List ItemList

    ReadFile()
    WriteFile()
}

Class ClientDataBase{
    List ClientList

    ReadFile()
    WriteFile()
}


Class FileReader{
    void read()
    void write()
}

Class Client{
    String name
    String id
    String phone

    void identify()
}

Class Item{
    String name
    String id
    long price

    void identify()
}

Class Controller{
    Item list
    Client list

    void addItem(FileReader())
    void removeItem()

    void createClient()
    void loginClient()
}



@enduml