@startuml
@startuml
Environment <-- Car
Environment <-- Rain
Environment <-- Weakness
Snail --> Environment
Game <-- Snail
Game <-- Environment
Game <-- Well
Game <-- Calendar


Class Game{
-Well well
-Snail snail
-Calendar calendar
-Rain rain
-Car car
}


Class Snail{
-boolvida
}

Class Well{
-Snail snail
-int waterDepth
-int snailDepth
}

Class Calendar{
int Day

+Calendar()
+public void nextDay()
+public int get Day()
}

Abstract Environment{
-String Problem

+Environment(String Problem)
}

Class Rain{
+TypeOfRain()
}

Class Weakness{
+Weakness(String)
}

Class Car{
+Car()
}
@enduml
@enduml