@startuml
class Mole {
 - String name
 - String avatar
 - boolean beaten
 + Mole()
 + Mole(String name)
 + getName() : String
 + setName(String name) : void
 + getAvatar() : String
 + setAvatar(String appereance) : void
 + isBeaten() : boolean
 + setBeaten(boolean isBeaten) : void
}

class Board {
  - List<List<Hole>> holes
  + Board()
  + Board(int holes)
  + showBoard() : void
  + beatenHole() : Hole
}
class Hole{
  - String aspect
  - Mole mole
  + Hole()
  + Hole(Mole mole)
  + getAspect() : String
  + setAspect(String aspect) : void
  + getMole() : Mole
  + setMole(Mole mole) : void
  - showMoleInside() : String
  - isMoleInside() : boolean
}
class Game{
  - Board board
  + Game()
  + Game(Board board)
  + showMenu() : void
  + startToPlay() : void
  - endPlaying() : void
}

class Main{
  + main()
}

Hole o-- Mole
Board *-- Hole
Game *-- Board
Main o-- Game
@enduml